CREATE TABLE `formulario_teste`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(15) NOT NULL,
  `ace_f_juazeiro` VARCHAR(15) NOT NULL,
  `trabalha_escritorio` VARCHAR(15) NOT NULL,
  `trabalha_hibrido` VARCHAR(15) NOT NULL,
  `trabalha_meio_p` VARCHAR(15) NOT NULL,
  `p_comp` VARCHAR(15) NOT NULL,
  `p_cell` VARCHAR(15) NOT NULL,
  `p_xp_proficional` VARCHAR(15) NOT NULL,
  `area_cand` VARCHAR(15) NOT NULL,
  `area_pt_cande` VARCHAR(15) NOT NULL,
  `tec_beck_end` VARCHAR(45) NOT NULL,
  `conhece_wp` VARCHAR(15) NULL,
  `conhece_elementor` VARCHAR(15) NULL,
  `conhece_low_no_code` VARCHAR(15) NULL,
  `tec_no_low_code` VARCHAR(45) NULL,
  `nivel_prof` VARCHAR(15) NOT NULL,
  `tempo_trabalhado` VARCHAR(15) NOT NULL,
  `aceita_exame` VARCHAR(15) NOT NULL,
  `possui_ingles` VARCHAR(15) NOT NULL,
  `nv_ingles` VARCHAR(15) NOT NULL,
  `nod_contrat` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`));
